export const UNITS = {
	'Unitless': 0,
	'Inches': 1,
	'Feet': 2,
	'Miles': 3,
	'Millimeters': 4,
	'Centimeters': 5,
	'Meters': 6,
	'Kilometers': 7,
	'Microinches': 8,
	'Mils': 9,
	'Yards': 10,
	'Angstroms': 11,
	'Nanometers': 12,
	'Microns': 13,
	'Decimeters': 14,
	'Decameters': 15,
	'Hectometers': 16,
	'Gigameters': 17,
	'Astronomical units': 18,
	'Light years': 19,
	'Parsecs': 20,
	'US Survey Feet': 21,
	'US Survey Inch': 22,
	'US Survey Yard': 23,
	'US Survey Mile': 24
};